// Generated by gencpp from file my_ros_msgs/CircleAreaRequest.msg
// DO NOT EDIT!


#ifndef MY_ROS_MSGS_MESSAGE_CIRCLEAREAREQUEST_H
#define MY_ROS_MSGS_MESSAGE_CIRCLEAREAREQUEST_H


#include <string>
#include <vector>
#include <map>

#include <ros/types.h>
#include <ros/serialization.h>
#include <ros/builtin_message_traits.h>
#include <ros/message_operations.h>


namespace my_ros_msgs
{
template <class ContainerAllocator>
struct CircleAreaRequest_
{
  typedef CircleAreaRequest_<ContainerAllocator> Type;

  CircleAreaRequest_()
    : radius(0.0)  {
    }
  CircleAreaRequest_(const ContainerAllocator& _alloc)
    : radius(0.0)  {
  (void)_alloc;
    }



   typedef double _radius_type;
  _radius_type radius;





  typedef boost::shared_ptr< ::my_ros_msgs::CircleAreaRequest_<ContainerAllocator> > Ptr;
  typedef boost::shared_ptr< ::my_ros_msgs::CircleAreaRequest_<ContainerAllocator> const> ConstPtr;

}; // struct CircleAreaRequest_

typedef ::my_ros_msgs::CircleAreaRequest_<std::allocator<void> > CircleAreaRequest;

typedef boost::shared_ptr< ::my_ros_msgs::CircleAreaRequest > CircleAreaRequestPtr;
typedef boost::shared_ptr< ::my_ros_msgs::CircleAreaRequest const> CircleAreaRequestConstPtr;

// constants requiring out of line definition



template<typename ContainerAllocator>
std::ostream& operator<<(std::ostream& s, const ::my_ros_msgs::CircleAreaRequest_<ContainerAllocator> & v)
{
ros::message_operations::Printer< ::my_ros_msgs::CircleAreaRequest_<ContainerAllocator> >::stream(s, "", v);
return s;
}

} // namespace my_ros_msgs

namespace ros
{
namespace message_traits
{



// BOOLTRAITS {'IsFixedSize': True, 'IsMessage': True, 'HasHeader': False}
// {'std_msgs': ['/opt/ros/kinetic/share/std_msgs/cmake/../msg'], 'my_ros_msgs': ['/home/manikanda/catkin_ws/src/my_ros_msgs/msg']}

// !!!!!!!!!!! ['__class__', '__delattr__', '__dict__', '__doc__', '__eq__', '__format__', '__getattribute__', '__hash__', '__init__', '__module__', '__ne__', '__new__', '__reduce__', '__reduce_ex__', '__repr__', '__setattr__', '__sizeof__', '__str__', '__subclasshook__', '__weakref__', '_parsed_fields', 'constants', 'fields', 'full_name', 'has_header', 'header_present', 'names', 'package', 'parsed_fields', 'short_name', 'text', 'types']




template <class ContainerAllocator>
struct IsFixedSize< ::my_ros_msgs::CircleAreaRequest_<ContainerAllocator> >
  : TrueType
  { };

template <class ContainerAllocator>
struct IsFixedSize< ::my_ros_msgs::CircleAreaRequest_<ContainerAllocator> const>
  : TrueType
  { };

template <class ContainerAllocator>
struct IsMessage< ::my_ros_msgs::CircleAreaRequest_<ContainerAllocator> >
  : TrueType
  { };

template <class ContainerAllocator>
struct IsMessage< ::my_ros_msgs::CircleAreaRequest_<ContainerAllocator> const>
  : TrueType
  { };

template <class ContainerAllocator>
struct HasHeader< ::my_ros_msgs::CircleAreaRequest_<ContainerAllocator> >
  : FalseType
  { };

template <class ContainerAllocator>
struct HasHeader< ::my_ros_msgs::CircleAreaRequest_<ContainerAllocator> const>
  : FalseType
  { };


template<class ContainerAllocator>
struct MD5Sum< ::my_ros_msgs::CircleAreaRequest_<ContainerAllocator> >
{
  static const char* value()
  {
    return "34d1b51a3aa2a07a0194bc3c5de27677";
  }

  static const char* value(const ::my_ros_msgs::CircleAreaRequest_<ContainerAllocator>&) { return value(); }
  static const uint64_t static_value1 = 0x34d1b51a3aa2a07aULL;
  static const uint64_t static_value2 = 0x0194bc3c5de27677ULL;
};

template<class ContainerAllocator>
struct DataType< ::my_ros_msgs::CircleAreaRequest_<ContainerAllocator> >
{
  static const char* value()
  {
    return "my_ros_msgs/CircleAreaRequest";
  }

  static const char* value(const ::my_ros_msgs::CircleAreaRequest_<ContainerAllocator>&) { return value(); }
};

template<class ContainerAllocator>
struct Definition< ::my_ros_msgs::CircleAreaRequest_<ContainerAllocator> >
{
  static const char* value()
  {
    return "float64 radius\n\
";
  }

  static const char* value(const ::my_ros_msgs::CircleAreaRequest_<ContainerAllocator>&) { return value(); }
};

} // namespace message_traits
} // namespace ros

namespace ros
{
namespace serialization
{

  template<class ContainerAllocator> struct Serializer< ::my_ros_msgs::CircleAreaRequest_<ContainerAllocator> >
  {
    template<typename Stream, typename T> inline static void allInOne(Stream& stream, T m)
    {
      stream.next(m.radius);
    }

    ROS_DECLARE_ALLINONE_SERIALIZER
  }; // struct CircleAreaRequest_

} // namespace serialization
} // namespace ros

namespace ros
{
namespace message_operations
{

template<class ContainerAllocator>
struct Printer< ::my_ros_msgs::CircleAreaRequest_<ContainerAllocator> >
{
  template<typename Stream> static void stream(Stream& s, const std::string& indent, const ::my_ros_msgs::CircleAreaRequest_<ContainerAllocator>& v)
  {
    s << indent << "radius: ";
    Printer<double>::stream(s, indent + "  ", v.radius);
  }
};

} // namespace message_operations
} // namespace ros

#endif // MY_ROS_MSGS_MESSAGE_CIRCLEAREAREQUEST_H
