// Generated by gencpp from file my_ros_msgs/CircleArea.msg
// DO NOT EDIT!


#ifndef MY_ROS_MSGS_MESSAGE_CIRCLEAREA_H
#define MY_ROS_MSGS_MESSAGE_CIRCLEAREA_H

#include <ros/service_traits.h>


#include <my_ros_msgs/CircleAreaRequest.h>
#include <my_ros_msgs/CircleAreaResponse.h>


namespace my_ros_msgs
{

struct CircleArea
{

typedef CircleAreaRequest Request;
typedef CircleAreaResponse Response;
Request request;
Response response;

typedef Request RequestType;
typedef Response ResponseType;

}; // struct CircleArea
} // namespace my_ros_msgs


namespace ros
{
namespace service_traits
{


template<>
struct MD5Sum< ::my_ros_msgs::CircleArea > {
  static const char* value()
  {
    return "c314357897f85c5c2498418b07dbcead";
  }

  static const char* value(const ::my_ros_msgs::CircleArea&) { return value(); }
};

template<>
struct DataType< ::my_ros_msgs::CircleArea > {
  static const char* value()
  {
    return "my_ros_msgs/CircleArea";
  }

  static const char* value(const ::my_ros_msgs::CircleArea&) { return value(); }
};


// service_traits::MD5Sum< ::my_ros_msgs::CircleAreaRequest> should match 
// service_traits::MD5Sum< ::my_ros_msgs::CircleArea > 
template<>
struct MD5Sum< ::my_ros_msgs::CircleAreaRequest>
{
  static const char* value()
  {
    return MD5Sum< ::my_ros_msgs::CircleArea >::value();
  }
  static const char* value(const ::my_ros_msgs::CircleAreaRequest&)
  {
    return value();
  }
};

// service_traits::DataType< ::my_ros_msgs::CircleAreaRequest> should match 
// service_traits::DataType< ::my_ros_msgs::CircleArea > 
template<>
struct DataType< ::my_ros_msgs::CircleAreaRequest>
{
  static const char* value()
  {
    return DataType< ::my_ros_msgs::CircleArea >::value();
  }
  static const char* value(const ::my_ros_msgs::CircleAreaRequest&)
  {
    return value();
  }
};

// service_traits::MD5Sum< ::my_ros_msgs::CircleAreaResponse> should match 
// service_traits::MD5Sum< ::my_ros_msgs::CircleArea > 
template<>
struct MD5Sum< ::my_ros_msgs::CircleAreaResponse>
{
  static const char* value()
  {
    return MD5Sum< ::my_ros_msgs::CircleArea >::value();
  }
  static const char* value(const ::my_ros_msgs::CircleAreaResponse&)
  {
    return value();
  }
};

// service_traits::DataType< ::my_ros_msgs::CircleAreaResponse> should match 
// service_traits::DataType< ::my_ros_msgs::CircleArea > 
template<>
struct DataType< ::my_ros_msgs::CircleAreaResponse>
{
  static const char* value()
  {
    return DataType< ::my_ros_msgs::CircleArea >::value();
  }
  static const char* value(const ::my_ros_msgs::CircleAreaResponse&)
  {
    return value();
  }
};

} // namespace service_traits
} // namespace ros

#endif // MY_ROS_MSGS_MESSAGE_CIRCLEAREA_H
