// Generated by gencpp from file my_ros_msgs/set_ledRequest.msg
// DO NOT EDIT!


#ifndef MY_ROS_MSGS_MESSAGE_SET_LEDREQUEST_H
#define MY_ROS_MSGS_MESSAGE_SET_LEDREQUEST_H


#include <string>
#include <vector>
#include <map>

#include <ros/types.h>
#include <ros/serialization.h>
#include <ros/builtin_message_traits.h>
#include <ros/message_operations.h>


namespace my_ros_msgs
{
template <class ContainerAllocator>
struct set_ledRequest_
{
  typedef set_ledRequest_<ContainerAllocator> Type;

  set_ledRequest_()
    : led_num(0)
    , state(false)  {
    }
  set_ledRequest_(const ContainerAllocator& _alloc)
    : led_num(0)
    , state(false)  {
  (void)_alloc;
    }



   typedef int64_t _led_num_type;
  _led_num_type led_num;

   typedef uint8_t _state_type;
  _state_type state;





  typedef boost::shared_ptr< ::my_ros_msgs::set_ledRequest_<ContainerAllocator> > Ptr;
  typedef boost::shared_ptr< ::my_ros_msgs::set_ledRequest_<ContainerAllocator> const> ConstPtr;

}; // struct set_ledRequest_

typedef ::my_ros_msgs::set_ledRequest_<std::allocator<void> > set_ledRequest;

typedef boost::shared_ptr< ::my_ros_msgs::set_ledRequest > set_ledRequestPtr;
typedef boost::shared_ptr< ::my_ros_msgs::set_ledRequest const> set_ledRequestConstPtr;

// constants requiring out of line definition



template<typename ContainerAllocator>
std::ostream& operator<<(std::ostream& s, const ::my_ros_msgs::set_ledRequest_<ContainerAllocator> & v)
{
ros::message_operations::Printer< ::my_ros_msgs::set_ledRequest_<ContainerAllocator> >::stream(s, "", v);
return s;
}

} // namespace my_ros_msgs

namespace ros
{
namespace message_traits
{



// BOOLTRAITS {'IsFixedSize': True, 'IsMessage': True, 'HasHeader': False}
// {'std_msgs': ['/opt/ros/kinetic/share/std_msgs/cmake/../msg'], 'my_ros_msgs': ['/home/manikanda/catkin_ws/src/my_ros_msgs/msg']}

// !!!!!!!!!!! ['__class__', '__delattr__', '__dict__', '__doc__', '__eq__', '__format__', '__getattribute__', '__hash__', '__init__', '__module__', '__ne__', '__new__', '__reduce__', '__reduce_ex__', '__repr__', '__setattr__', '__sizeof__', '__str__', '__subclasshook__', '__weakref__', '_parsed_fields', 'constants', 'fields', 'full_name', 'has_header', 'header_present', 'names', 'package', 'parsed_fields', 'short_name', 'text', 'types']




template <class ContainerAllocator>
struct IsFixedSize< ::my_ros_msgs::set_ledRequest_<ContainerAllocator> >
  : TrueType
  { };

template <class ContainerAllocator>
struct IsFixedSize< ::my_ros_msgs::set_ledRequest_<ContainerAllocator> const>
  : TrueType
  { };

template <class ContainerAllocator>
struct IsMessage< ::my_ros_msgs::set_ledRequest_<ContainerAllocator> >
  : TrueType
  { };

template <class ContainerAllocator>
struct IsMessage< ::my_ros_msgs::set_ledRequest_<ContainerAllocator> const>
  : TrueType
  { };

template <class ContainerAllocator>
struct HasHeader< ::my_ros_msgs::set_ledRequest_<ContainerAllocator> >
  : FalseType
  { };

template <class ContainerAllocator>
struct HasHeader< ::my_ros_msgs::set_ledRequest_<ContainerAllocator> const>
  : FalseType
  { };


template<class ContainerAllocator>
struct MD5Sum< ::my_ros_msgs::set_ledRequest_<ContainerAllocator> >
{
  static const char* value()
  {
    return "93a4930090c402a598366628fe79c1f8";
  }

  static const char* value(const ::my_ros_msgs::set_ledRequest_<ContainerAllocator>&) { return value(); }
  static const uint64_t static_value1 = 0x93a4930090c402a5ULL;
  static const uint64_t static_value2 = 0x98366628fe79c1f8ULL;
};

template<class ContainerAllocator>
struct DataType< ::my_ros_msgs::set_ledRequest_<ContainerAllocator> >
{
  static const char* value()
  {
    return "my_ros_msgs/set_ledRequest";
  }

  static const char* value(const ::my_ros_msgs::set_ledRequest_<ContainerAllocator>&) { return value(); }
};

template<class ContainerAllocator>
struct Definition< ::my_ros_msgs::set_ledRequest_<ContainerAllocator> >
{
  static const char* value()
  {
    return "int64 led_num\n\
bool state\n\
";
  }

  static const char* value(const ::my_ros_msgs::set_ledRequest_<ContainerAllocator>&) { return value(); }
};

} // namespace message_traits
} // namespace ros

namespace ros
{
namespace serialization
{

  template<class ContainerAllocator> struct Serializer< ::my_ros_msgs::set_ledRequest_<ContainerAllocator> >
  {
    template<typename Stream, typename T> inline static void allInOne(Stream& stream, T m)
    {
      stream.next(m.led_num);
      stream.next(m.state);
    }

    ROS_DECLARE_ALLINONE_SERIALIZER
  }; // struct set_ledRequest_

} // namespace serialization
} // namespace ros

namespace ros
{
namespace message_operations
{

template<class ContainerAllocator>
struct Printer< ::my_ros_msgs::set_ledRequest_<ContainerAllocator> >
{
  template<typename Stream> static void stream(Stream& s, const std::string& indent, const ::my_ros_msgs::set_ledRequest_<ContainerAllocator>& v)
  {
    s << indent << "led_num: ";
    Printer<int64_t>::stream(s, indent + "  ", v.led_num);
    s << indent << "state: ";
    Printer<uint8_t>::stream(s, indent + "  ", v.state);
  }
};

} // namespace message_operations
} // namespace ros

#endif // MY_ROS_MSGS_MESSAGE_SET_LEDREQUEST_H
