// Generated by gencpp from file my_ros_msgs/set_ledResponse.msg
// DO NOT EDIT!


#ifndef MY_ROS_MSGS_MESSAGE_SET_LEDRESPONSE_H
#define MY_ROS_MSGS_MESSAGE_SET_LEDRESPONSE_H


#include <string>
#include <vector>
#include <map>

#include <ros/types.h>
#include <ros/serialization.h>
#include <ros/builtin_message_traits.h>
#include <ros/message_operations.h>


namespace my_ros_msgs
{
template <class ContainerAllocator>
struct set_ledResponse_
{
  typedef set_ledResponse_<ContainerAllocator> Type;

  set_ledResponse_()
    : status()  {
    }
  set_ledResponse_(const ContainerAllocator& _alloc)
    : status(_alloc)  {
  (void)_alloc;
    }



   typedef std::basic_string<char, std::char_traits<char>, typename ContainerAllocator::template rebind<char>::other >  _status_type;
  _status_type status;





  typedef boost::shared_ptr< ::my_ros_msgs::set_ledResponse_<ContainerAllocator> > Ptr;
  typedef boost::shared_ptr< ::my_ros_msgs::set_ledResponse_<ContainerAllocator> const> ConstPtr;

}; // struct set_ledResponse_

typedef ::my_ros_msgs::set_ledResponse_<std::allocator<void> > set_ledResponse;

typedef boost::shared_ptr< ::my_ros_msgs::set_ledResponse > set_ledResponsePtr;
typedef boost::shared_ptr< ::my_ros_msgs::set_ledResponse const> set_ledResponseConstPtr;

// constants requiring out of line definition



template<typename ContainerAllocator>
std::ostream& operator<<(std::ostream& s, const ::my_ros_msgs::set_ledResponse_<ContainerAllocator> & v)
{
ros::message_operations::Printer< ::my_ros_msgs::set_ledResponse_<ContainerAllocator> >::stream(s, "", v);
return s;
}

} // namespace my_ros_msgs

namespace ros
{
namespace message_traits
{



// BOOLTRAITS {'IsFixedSize': False, 'IsMessage': True, 'HasHeader': False}
// {'std_msgs': ['/opt/ros/kinetic/share/std_msgs/cmake/../msg'], 'my_ros_msgs': ['/home/manikanda/catkin_ws/src/my_ros_msgs/msg']}

// !!!!!!!!!!! ['__class__', '__delattr__', '__dict__', '__doc__', '__eq__', '__format__', '__getattribute__', '__hash__', '__init__', '__module__', '__ne__', '__new__', '__reduce__', '__reduce_ex__', '__repr__', '__setattr__', '__sizeof__', '__str__', '__subclasshook__', '__weakref__', '_parsed_fields', 'constants', 'fields', 'full_name', 'has_header', 'header_present', 'names', 'package', 'parsed_fields', 'short_name', 'text', 'types']




template <class ContainerAllocator>
struct IsFixedSize< ::my_ros_msgs::set_ledResponse_<ContainerAllocator> >
  : FalseType
  { };

template <class ContainerAllocator>
struct IsFixedSize< ::my_ros_msgs::set_ledResponse_<ContainerAllocator> const>
  : FalseType
  { };

template <class ContainerAllocator>
struct IsMessage< ::my_ros_msgs::set_ledResponse_<ContainerAllocator> >
  : TrueType
  { };

template <class ContainerAllocator>
struct IsMessage< ::my_ros_msgs::set_ledResponse_<ContainerAllocator> const>
  : TrueType
  { };

template <class ContainerAllocator>
struct HasHeader< ::my_ros_msgs::set_ledResponse_<ContainerAllocator> >
  : FalseType
  { };

template <class ContainerAllocator>
struct HasHeader< ::my_ros_msgs::set_ledResponse_<ContainerAllocator> const>
  : FalseType
  { };


template<class ContainerAllocator>
struct MD5Sum< ::my_ros_msgs::set_ledResponse_<ContainerAllocator> >
{
  static const char* value()
  {
    return "4fe5af303955c287688e7347e9b00278";
  }

  static const char* value(const ::my_ros_msgs::set_ledResponse_<ContainerAllocator>&) { return value(); }
  static const uint64_t static_value1 = 0x4fe5af303955c287ULL;
  static const uint64_t static_value2 = 0x688e7347e9b00278ULL;
};

template<class ContainerAllocator>
struct DataType< ::my_ros_msgs::set_ledResponse_<ContainerAllocator> >
{
  static const char* value()
  {
    return "my_ros_msgs/set_ledResponse";
  }

  static const char* value(const ::my_ros_msgs::set_ledResponse_<ContainerAllocator>&) { return value(); }
};

template<class ContainerAllocator>
struct Definition< ::my_ros_msgs::set_ledResponse_<ContainerAllocator> >
{
  static const char* value()
  {
    return "string status\n\
\n\
";
  }

  static const char* value(const ::my_ros_msgs::set_ledResponse_<ContainerAllocator>&) { return value(); }
};

} // namespace message_traits
} // namespace ros

namespace ros
{
namespace serialization
{

  template<class ContainerAllocator> struct Serializer< ::my_ros_msgs::set_ledResponse_<ContainerAllocator> >
  {
    template<typename Stream, typename T> inline static void allInOne(Stream& stream, T m)
    {
      stream.next(m.status);
    }

    ROS_DECLARE_ALLINONE_SERIALIZER
  }; // struct set_ledResponse_

} // namespace serialization
} // namespace ros

namespace ros
{
namespace message_operations
{

template<class ContainerAllocator>
struct Printer< ::my_ros_msgs::set_ledResponse_<ContainerAllocator> >
{
  template<typename Stream> static void stream(Stream& s, const std::string& indent, const ::my_ros_msgs::set_ledResponse_<ContainerAllocator>& v)
  {
    s << indent << "status: ";
    Printer<std::basic_string<char, std::char_traits<char>, typename ContainerAllocator::template rebind<char>::other > >::stream(s, indent + "  ", v.status);
  }
};

} // namespace message_operations
} // namespace ros

#endif // MY_ROS_MSGS_MESSAGE_SET_LEDRESPONSE_H
