// Generated by gencpp from file my_ros_msgs/set_led.msg
// DO NOT EDIT!


#ifndef MY_ROS_MSGS_MESSAGE_SET_LED_H
#define MY_ROS_MSGS_MESSAGE_SET_LED_H

#include <ros/service_traits.h>


#include <my_ros_msgs/set_ledRequest.h>
#include <my_ros_msgs/set_ledResponse.h>


namespace my_ros_msgs
{

struct set_led
{

typedef set_ledRequest Request;
typedef set_ledResponse Response;
Request request;
Response response;

typedef Request RequestType;
typedef Response ResponseType;

}; // struct set_led
} // namespace my_ros_msgs


namespace ros
{
namespace service_traits
{


template<>
struct MD5Sum< ::my_ros_msgs::set_led > {
  static const char* value()
  {
    return "13151403018f57191e13ddc5e2e35789";
  }

  static const char* value(const ::my_ros_msgs::set_led&) { return value(); }
};

template<>
struct DataType< ::my_ros_msgs::set_led > {
  static const char* value()
  {
    return "my_ros_msgs/set_led";
  }

  static const char* value(const ::my_ros_msgs::set_led&) { return value(); }
};


// service_traits::MD5Sum< ::my_ros_msgs::set_ledRequest> should match 
// service_traits::MD5Sum< ::my_ros_msgs::set_led > 
template<>
struct MD5Sum< ::my_ros_msgs::set_ledRequest>
{
  static const char* value()
  {
    return MD5Sum< ::my_ros_msgs::set_led >::value();
  }
  static const char* value(const ::my_ros_msgs::set_ledRequest&)
  {
    return value();
  }
};

// service_traits::DataType< ::my_ros_msgs::set_ledRequest> should match 
// service_traits::DataType< ::my_ros_msgs::set_led > 
template<>
struct DataType< ::my_ros_msgs::set_ledRequest>
{
  static const char* value()
  {
    return DataType< ::my_ros_msgs::set_led >::value();
  }
  static const char* value(const ::my_ros_msgs::set_ledRequest&)
  {
    return value();
  }
};

// service_traits::MD5Sum< ::my_ros_msgs::set_ledResponse> should match 
// service_traits::MD5Sum< ::my_ros_msgs::set_led > 
template<>
struct MD5Sum< ::my_ros_msgs::set_ledResponse>
{
  static const char* value()
  {
    return MD5Sum< ::my_ros_msgs::set_led >::value();
  }
  static const char* value(const ::my_ros_msgs::set_ledResponse&)
  {
    return value();
  }
};

// service_traits::DataType< ::my_ros_msgs::set_ledResponse> should match 
// service_traits::DataType< ::my_ros_msgs::set_led > 
template<>
struct DataType< ::my_ros_msgs::set_ledResponse>
{
  static const char* value()
  {
    return DataType< ::my_ros_msgs::set_led >::value();
  }
  static const char* value(const ::my_ros_msgs::set_ledResponse&)
  {
    return value();
  }
};

} // namespace service_traits
} // namespace ros

#endif // MY_ROS_MSGS_MESSAGE_SET_LED_H
